import type { NextPage } from 'next';
import Head from 'next/head';
import React from "react";

import App from "./_app";
import "bootstrap/dist/css/bootstrap.css";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      </main>

     
    </div>
  )
}

export default Home
